### ISSUE TITLE
windows预安装版启动报错

### ISSUE THREAD

**Issue by CandyACE** [jianchang512/ChatTTS-ui#10]
2024-05-31 13:33:30,015 - modelscope - INFO - PyTorch version 2.3.0+cu118 Found.
2024-05-31 13:33:30,016 - modelscope - INFO - Loading ast index from C:\Users\tstwt\.cache\modelscope\ast_indexer
2024-05-31 13:33:30,017 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 d41d8cd98f00b204e9800998ecf8427e and a total number of 0 components indexed
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=2, read=2, redirect=None, status=None)) after connection broken by 'FileNotFoundError(2, 'No such file or directory')': /api/v1/models/pzc163/chatTTS/revisions
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=2, read=2, redirect=None, status=None)) after connection broken by 'FileNotFoundError(2, 'No such file or directory')': /api/v1/models/pzc163/chatTTS/revisions
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 779, in urlopen
  File "urllib3\connectionpool.py", line 1048, in _prepare_proxy
  File "urllib3\connection.py", line 625, in connect
  File "urllib3\connection.py", line 699, in _connect_tls_proxy
  File "urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 589, in send
  File "urllib3\connectionpool.py", line 877, in urlopen
  File "urllib3\connectionpool.py", line 877, in urlopen
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/pzc163/chatTTS/revisions (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 43, in <module>
  File "modelscope\hub\snapshot_download.py", line 98, in snapshot_download
  File "modelscope\hub\api.py", line 497, in get_valid_revision_detail
  File "modelscope\hub\api.py", line 575, in get_model_branches_and_tags_details
  File "requests\sessions.py", line 602, in get
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 616, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.modelscope.cn', port=443): Max retries exceeded with url: /api/v1/models/pzc163/chatTTS/revisions (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))
[34668] Failed to execute script 'app' due to unhandled exception!

**Comment by jianchang512** [comment]
关掉代理。modelscope 不可使用代理下载模型

**Comment by CandyACE** [comment]
ok
