### ISSUE TITLE
Mac OS安装报错

### ISSUE THREAD

**Issue by voralal** [jianchang512/ChatTTS-ui#11]
Traceback (most recent call last):
  File "/Users/XXX/chattts/chatTTS-ui/app.py", line 41, in <module>
    chat.load_models(source="local",local_path=CHATTTS_DIR)
  File "/Users/XXX/chattts/chatTTS-ui/ChatTTS/core.py", line 58, in load_models
    self._load(**{k: os.path.join(local_path, v) for k, v in OmegaConf.load(os.path.join(local_path, 'config', 'path.yaml')).items()})
  File "/Users/XXX/chattts/chatTTS-ui/ChatTTS/core.py", line 100, in _load
    self.pretrain_models['spk_stat'] = torch.load(spk_stat_path).to(device)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/chattts/chatTTS-ui/venv/lib/python3.12/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/chattts/chatTTS-ui/venv/lib/python3.12/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by voralal** [comment]
今天git了v0.87版，仍然是python 3.12，安装成功，关闭这个issue吧
