### ISSUE TITLE
mac 源码部署，启动项目python3 app.py 提示 缺少 spk_stat.pt 文件

### ISSUE THREAD

**Issue by hellloveyy** [jianchang512/ChatTTS-ui#12]
/Users/lizhihua/data/chattts/ChatTTS-ui/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
2024-05-31 14:27:55,950 - modelscope - INFO - PyTorch version 2.3.0 Found.
2024-05-31 14:27:55,950 - modelscope - INFO - Loading ast index from /Users/lizhihua/.cache/modelscope/ast_indexer
2024-05-31 14:27:56,037 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 0203f73c3dee56de722d0d1a0f3866af and a total number of 976 components indexed
INFO:ChatTTS.core:Load from local: /Users/lizhihua/data/chattts/ChatTTS-ui/models/pzc163/chatTTS
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
Traceback (most recent call last):
  File "/Users/lizhihua/data/chattts/ChatTTS-ui/app.py", line 45, in <module>
    chat.load_models(source="local",local_path=CHATTTS_DIR)
  File "/Users/lizhihua/data/chattts/ChatTTS-ui/ChatTTS/core.py", line 61, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()}, **kwargs)
  File "/Users/lizhihua/data/chattts/ChatTTS-ui/ChatTTS/core.py", line 105, in _load
    assert os.path.exists(spk_stat_path), f'Missing spk_stat.pt: {spk_stat_path}'
AssertionError: Missing spk_stat.pt: /Users/lizhihua/data/chattts/ChatTTS-ui/models/pzc163/chatTTS/asset/spk_stat.pt

**Comment by hellloveyy** [comment]
安装环境所需步骤无报错，日志如下
pip3 install -r requirements.txt


Requirement already satisfied: Flask in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: ipython in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (8.18.1)
Requirement already satisfied: modelscope in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.14.0)
Requirement already satisfied: numpy==1.26.4 in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.26.4)
Requirement already satisfied: omegaconf in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (2.3.0)
Requirement already satisfied: python-dotenv in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.0.1)
Requirement already satisfied: requests in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2.32.3)
Requirement already satisfied: soundfile in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (0.12.1)
Requirement already satisfied: tokenizers in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (0.19.1)
Requirement already satisfied: transformers in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (4.41.2)
Requirement already satisfied: vector-quantize-pytorch in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (1.14.24)
Requirement already satisfied: vocos in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (0.1.0)
Requirement already satisfied: waitress in ./venv/lib/python3.9/site-packages (from -r requirements.txt (line 13)) (3.0.0)
Requirement already satisfied: Werkzeug>=3.0.0 in ./venv/lib/python3.9/site-packages (from Flask->-r requirements.txt (line 1)) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in ./venv/lib/python3.9/site-packages (from Flask->-r requirements.txt (line 1)) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in ./venv/lib/python3.9/site-packages (from Flask->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: click>=8.1.3 in ./venv/lib/python3.9/site-packages (from Flask->-r requirements.txt (line 1)) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in ./venv/lib/python3.9/site-packages (from Flask->-r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./venv/lib/python3.9/site-packages (from Flask->-r requirements.txt (line 1)) (7.1.0)
Requirement already satisfied: decorator in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (5.1.1)
Requirement already satisfied: jedi>=0.16 in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (0.19.1)
Requirement already satisfied: matplotlib-inline in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (3.0.45)
Requirement already satisfied: pygments>=2.4.0 in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: stack-data in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (0.6.3)
Requirement already satisfied: traitlets>=5 in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (5.14.3)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (4.12.0)
Requirement already satisfied: exceptiongroup in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: pexpect>4.3 in ./venv/lib/python3.9/site-packages (from ipython->-r requirements.txt (line 2)) (4.9.0)
Requirement already satisfied: addict in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: attrs in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (23.2.0)
Requirement already satisfied: datasets<2.19.0,>=2.16.0 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (2.18.0)
Requirement already satisfied: einops in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (0.8.0)
Requirement already satisfied: filelock>=3.3.0 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (3.14.0)
Requirement already satisfied: gast>=0.2.2 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (0.5.4)
Requirement already satisfied: huggingface-hub in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (0.23.2)
Requirement already satisfied: oss2 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (2.18.5)
Requirement already satisfied: pandas in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (2.2.2)
Requirement already satisfied: Pillow>=6.2.0 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (10.3.0)
Requirement already satisfied: pyarrow!=9.0.0,>=6.0.0 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (16.1.0)
Requirement already satisfied: python-dateutil>=2.1 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: pyyaml in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (6.0.1)
Requirement already satisfied: scipy in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (1.13.1)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (58.0.4)
Requirement already satisfied: simplejson>=3.3.0 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (3.19.2)
Requirement already satisfied: sortedcontainers>=1.5.9 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: tqdm>=4.64.0 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (4.66.4)
Requirement already satisfied: urllib3>=1.26 in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (2.2.1)
Requirement already satisfied: yapf in ./venv/lib/python3.9/site-packages (from modelscope->-r requirements.txt (line 3)) (0.40.2)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in ./venv/lib/python3.9/site-packages (from omegaconf->-r requirements.txt (line 5)) (4.9.3)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.9/site-packages (from requests->-r requirements.txt (line 7)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.9/site-packages (from requests->-r requirements.txt (line 7)) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests->-r requirements.txt (line 7)) (2024.2.2)
Requirement already satisfied: cffi>=1.0 in ./venv/lib/python3.9/site-packages (from soundfile->-r requirements.txt (line 8)) (1.16.0)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.9/site-packages (from transformers->-r requirements.txt (line 10)) (24.0)
Requirement already satisfied: regex!=2019.12.17 in ./venv/lib/python3.9/site-packages (from transformers->-r requirements.txt (line 10)) (2024.5.15)
Requirement already satisfied: safetensors>=0.4.1 in ./venv/lib/python3.9/site-packages (from transformers->-r requirements.txt (line 10)) (0.4.3)
Requirement already satisfied: einx>=0.2.2 in ./venv/lib/python3.9/site-packages (from vector-quantize-pytorch->-r requirements.txt (line 11)) (0.2.2)
Requirement already satisfied: torch>=2.0 in ./venv/lib/python3.9/site-packages (from vector-quantize-pytorch->-r requirements.txt (line 11)) (2.3.0)
Requirement already satisfied: torchaudio in ./venv/lib/python3.9/site-packages (from vocos->-r requirements.txt (line 12)) (2.3.0)
Requirement already satisfied: encodec==0.1.1 in ./venv/lib/python3.9/site-packages (from vocos->-r requirements.txt (line 12)) (0.1.1)
Requirement already satisfied: pycparser in ./venv/lib/python3.9/site-packages (from cffi>=1.0->soundfile->-r requirements.txt (line 8)) (2.22)
Requirement already satisfied: pyarrow-hotfix in ./venv/lib/python3.9/site-packages (from datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in ./venv/lib/python3.9/site-packages (from datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (0.3.8)
Requirement already satisfied: xxhash in ./venv/lib/python3.9/site-packages (from datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (3.4.1)
Requirement already satisfied: multiprocess in ./venv/lib/python3.9/site-packages (from datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (0.70.16)
Requirement already satisfied: fsspec<=2024.2.0,>=2023.1.0 in ./venv/lib/python3.9/site-packages (from fsspec[http]<=2024.2.0,>=2023.1.0->datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (2024.2.0)
Requirement already satisfied: aiohttp in ./venv/lib/python3.9/site-packages (from datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (3.9.5)
Requirement already satisfied: sympy in ./venv/lib/python3.9/site-packages (from einx>=0.2.2->vector-quantize-pytorch->-r requirements.txt (line 11)) (1.12.1)
Requirement already satisfied: frozendict in ./venv/lib/python3.9/site-packages (from einx>=0.2.2->vector-quantize-pytorch->-r requirements.txt (line 11)) (2.4.4)
Requirement already satisfied: zipp>=0.5 in ./venv/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->Flask->-r requirements.txt (line 1)) (3.19.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in ./venv/lib/python3.9/site-packages (from jedi>=0.16->ipython->-r requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.9/site-packages (from Jinja2>=3.1.2->Flask->-r requirements.txt (line 1)) (2.1.5)
Requirement already satisfied: ptyprocess>=0.5 in ./venv/lib/python3.9/site-packages (from pexpect>4.3->ipython->-r requirements.txt (line 2)) (0.7.0)
Requirement already satisfied: wcwidth in ./venv/lib/python3.9/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->-r requirements.txt (line 2)) (0.2.13)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages (from python-dateutil>=2.1->modelscope->-r requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: networkx in ./venv/lib/python3.9/site-packages (from torch>=2.0->vector-quantize-pytorch->-r requirements.txt (line 11)) (3.2.1)
Requirement already satisfied: crcmod>=1.7 in ./venv/lib/python3.9/site-packages (from oss2->modelscope->-r requirements.txt (line 3)) (1.7)
Requirement already satisfied: pycryptodome>=3.4.7 in ./venv/lib/python3.9/site-packages (from oss2->modelscope->-r requirements.txt (line 3)) (3.20.0)
Requirement already satisfied: aliyun-python-sdk-kms>=2.4.1 in ./venv/lib/python3.9/site-packages (from oss2->modelscope->-r requirements.txt (line 3)) (2.16.3)
Requirement already satisfied: aliyun-python-sdk-core>=2.13.12 in ./venv/lib/python3.9/site-packages (from oss2->modelscope->-r requirements.txt (line 3)) (2.15.1)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.9/site-packages (from pandas->modelscope->-r requirements.txt (line 3)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in ./venv/lib/python3.9/site-packages (from pandas->modelscope->-r requirements.txt (line 3)) (2024.1)
Requirement already satisfied: executing>=1.2.0 in ./venv/lib/python3.9/site-packages (from stack-data->ipython->-r requirements.txt (line 2)) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in ./venv/lib/python3.9/site-packages (from stack-data->ipython->-r requirements.txt (line 2)) (2.4.1)
Requirement already satisfied: pure-eval in ./venv/lib/python3.9/site-packages (from stack-data->ipython->-r requirements.txt (line 2)) (0.2.2)
Requirement already satisfied: platformdirs>=3.5.1 in ./venv/lib/python3.9/site-packages (from yapf->modelscope->-r requirements.txt (line 3)) (4.2.2)
Requirement already satisfied: tomli>=2.0.1 in ./venv/lib/python3.9/site-packages (from yapf->modelscope->-r requirements.txt (line 3)) (2.0.1)
Requirement already satisfied: jmespath<1.0.0,>=0.9.3 in ./venv/lib/python3.9/site-packages (from aliyun-python-sdk-core>=2.13.12->oss2->modelscope->-r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: cryptography>=2.6.0 in ./venv/lib/python3.9/site-packages (from aliyun-python-sdk-core>=2.13.12->oss2->modelscope->-r requirements.txt (line 3)) (42.0.7)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.9/site-packages (from aiohttp->datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.9/site-packages (from aiohttp->datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.9/site-packages (from aiohttp->datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv/lib/python3.9/site-packages (from aiohttp->datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in ./venv/lib/python3.9/site-packages (from aiohttp->datasets<2.19.0,>=2.16.0->modelscope->-r requirements.txt (line 3)) (4.0.3)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in ./venv/lib/python3.9/site-packages (from sympy->einx>=0.2.2->vector-quantize-pytorch->-r requirements.txt (line 11)) (1.3.0)
(venv) ➜  ChatTTS-ui git:(main) pip3 install torch torchaudio
Requirement already satisfied: torch in ./venv/lib/python3.9/site-packages (2.3.0)
Requirement already satisfied: torchaudio in ./venv/lib/python3.9/site-packages (2.3.0)
Requirement already satisfied: filelock in ./venv/lib/python3.9/site-packages (from torch) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in ./venv/lib/python3.9/site-packages (from torch) (4.12.0)
Requirement already satisfied: sympy in ./venv/lib/python3.9/site-packages (from torch) (1.12.1)
Requirement already satisfied: networkx in ./venv/lib/python3.9/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in ./venv/lib/python3.9/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in ./venv/lib/python3.9/site-packages (from torch) (2024.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.9/site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in ./venv/lib/python3.9/site-packages (from sympy->torch) (1.3.0)

**Comment by hellloveyy** [comment]
![image](https://github.com/jianchang512/ChatTTS-ui/assets/14924943/d0a1ce5a-7962-41cc-b66d-9050654e3a29)
不好意思，没看到，close close
