### ISSUE TITLE
0.9版本compile=True报错

### ISSUE THREAD

**Issue by fengs2021** [jianchang512/ChatTTS-ui#126]
Starting...
2024-06-11 21:26:01,227 - modelscope - INFO - PyTorch version 2.2.0+cu118 Found.
2024-06-11 21:26:01,229 - modelscope - INFO - Loading ast index from C:\Users\liqih\.cache\modelscope\ast_indexer
2024-06-11 21:26:01,488 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 5a2531b9406c49ca9a886a774b34174c and a total number of 980 components indexed
INFO:ChatTTS.core:Load from local: F:/ChatTTS/models/pzc163/chatTTS
INFO:ChatTTS.core:use cuda:0
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
Traceback (most recent call last):
  File "F:\ChatTTS\app.py", line 64, in <module>
    chat.load_models(source="local",local_path=CHATTTS_DIR, device=None if device=='default' else device,compile=True if os.getenv('compile','true').lower()!='false' else False)
  File "F:\ChatTTS\ChatTTS\core.py", line 62, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()}, **kwargs)
  File "F:\ChatTTS\ChatTTS\core.py", line 103, in _load
    gpt.gpt.forward = torch.compile(gpt.gpt.forward,  backend='inductor', dynamic=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatTTS\venv\Lib\site-packages\torch\__init__.py", line 1795, in compile
    raise RuntimeError("Dynamo is not supported on Python 3.12+")
RuntimeError: Dynamo is not supported on Python 3.12+

**Comment by jianchang512** [comment]
不支持py3.12

**Comment by jianchang512** [comment]
1. 用 3.10
2. compile 设为False， True是启用推理优化，不是所有显卡、cuda、torch版本都支持

**Comment by fengs2021** [comment]
win平台不支持torch.compile
