### ISSUE TITLE
"Dynamo is not supported on Python 3.12+"

### ISSUE THREAD

**Issue by moffefei** [jianchang512/ChatTTS-ui#17]
要对python 版本降级么？

`INFO:ChatTTS.core:Load from local: D:/tools/100AIGC/chatTTS-ui/models\pzc163\chatTTS
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
Traceback (most recent call last):
  File "D:\tools\100AIGC\chatTTS-ui\app.py", line 45, in <module>
    chat.load_models(source="local",local_path=CHATTTS_DIR)
  File "D:\tools\100AIGC\chatTTS-ui\ChatTTS\core.py", line 61, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()}, **kwargs)
  File "D:\tools\100AIGC\chatTTS-ui\ChatTTS\core.py", line 102, in _load
    gpt.gpt.forward = torch.compile(gpt.gpt.forward,  backend='inductor', dynamic=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\100AIGC\chatTTS-ui\venv\Lib\site-packages\torch\__init__.py", line 1866, in compile
    raise RuntimeError("Dynamo is not supported on Python 3.12+")
RuntimeError: Dynamo is not supported on Python 3.12+

`

**Comment by moffefei** [comment]
用conda，11，启动成功。
![image](https://github.com/jianchang512/ChatTTS-ui/assets/132885305/12a893ab-ae33-44b7-81c1-bf5387e2cd6d)
