### ISSUE TITLE
通过源码编译的，执行报错了：IndexError: list index out of range

### ISSUE THREAD

**Issue by mybolide** [jianchang512/ChatTTS-ui#176]
通过源码编译的，执行报错了
ERROR:app:Exception on /tts [POST]
Traceback (most recent call last):
  File "E:\chatTTS-ui\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\chatTTS-ui\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\chatTTS-ui\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\chatTTS-ui\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\chatTTS-ui\app.py", line 268, in tts
    retext[-1]+=f" [uv_break] {short_text}"
    ~~~~~~^^^^
IndexError: list index out of range

**Comment by jianchang512** [comment]
重新拉取源码
