### ISSUE TITLE
cannot import name 'hf_hub_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by wisyemily** [jianchang512/ChatTTS-ui#179]
> 我也出现了这个问题，按照上面的方式安装后出现了新的问题（我的系统是 linux）： Traceback (most recent call last): File "/home/anlj/work/src/ChatTTS-ui-main/app.py", line 14, in import ChatTTS File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/**init**.py", line 1, in from .core import Chat File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/core.py", line 8, in from vocos import Vocos File "/home/anlj/.local/lib/python3.11/site-packages/vocos/**init**.py", line 1, in from vocos.pretrained import Vocos File "/home/anlj/.local/lib/python3.11/site-packages/vocos/pretrained.py", line 7, in from huggingface_hub import hf_hub_download ImportError: cannot import name 'hf_hub_download' from 'huggingface_hub' (/home/anlj/.local/lib/python3.11/site-packages/huggingface_hub/**init**.py)

这个问题怎么解决？我前几天能正常运行，今天一直报这个错，重新安装了环境依然报这个错误。

_Originally posted by @wisyemily in https://github.com/jianchang512/ChatTTS-ui/issues/84#issuecomment-2220721432_

**Comment by jianchang512** [comment]
`pip3 install --upgrade huggingface_hub`

**Comment by wisyemily** [comment]
已经是最新的了，依然报同样的错误。

**Comment by jianchang512** [comment]
`pip3 uninstall huggingace_hub`
`pip3 install huggingface_hub`

先卸载再安装试试

**Comment by wisyemily** [comment]
> `pip3 uninstall huggingace_hub` `pip3 install huggingface_hub`
> 
> 先卸载再安装试试

试过了。把虚拟环境重装了，同样还是报这个错误。我的是wsl环境。

**Comment by wisyemily** [comment]
这台机器，我切到windows上安装chattts-ui，也是报这个错误。安装原版chattts可以正常运行
