### ISSUE TITLE
windows 11 转换时发生内部错误

### ISSUE THREAD

**Issue by JiangLongLiu** [jianchang512/ChatTTS-ui#18]
启动正常，转换时报错。

![image](https://github.com/jianchang512/ChatTTS-ui/assets/7019907/d081a6fb-f3b5-4cbc-889d-b6962cb98e13)

日志信息：
```
venv) E:\openSource_workspace\chatTTS-ui>python app.py
2024-05-31 17:09:13,660 - modelscope - INFO - PyTorch version 2.3.0 Found.
2024-05-31 17:09:13,662 - modelscope - INFO - Loading ast index from C:\Users\liujianglong\.cache\modelscope\ast_indexer2024-05-31 17:09:13,760 - modelscope - INFO - No valid ast index found from C:\Users\liujianglong\.cache\modelscope\ast_indexer, generating ast index from prebuilt!
2024-05-31 17:09:13,875 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 20d6d72d7c727847862295a469dcf2cf and a total number of 976 components indexed
Downloading: 100%|████████████████████████████████████████████████████████████████| 4.16k/4.16k [00:00<00:00, 4.23MB/s]
INFO:ChatTTS.core:Load from local: E:/openSource_workspace/chatTTS-ui/models\pzc163\chatTTS
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
启动:['127.0.0.1', '9966']
  0%|                                                                                          | 0/384 [00:01<?, ?it/s]
[2024-05-31 17:09:25,237] ERROR in app: Exception on /tts [POST]
Traceback (most recent call last):
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\openSource_workspace\chatTTS-ui\app.py", line 118, in tts
    wavs = chat.infer([t for t in text.split("\n") if t.strip()], use_decoder=True,params_infer_code={'spk_emb': rand_spk} ,params_refine_text= {'prompt': prompt})
  File "E:\openSource_workspace\chatTTS-ui\ChatTTS\core.py", line 154, in infer
    text_tokens = refine_text(self.pretrain_models, text, **params_refine_text)['ids']
  File "E:\openSource_workspace\chatTTS-ui\ChatTTS\infer\api.py", line 114, in refine_text
    result = models['gpt'].generate(
  File "E:\openSource_workspace\chatTTS-ui\ChatTTS\model\gpt.py", line 203, in generate
    outputs = self.gpt.forward(**model_input, output_attentions=return_attn)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 940, in forward
    causal_mask = self._update_causal_mask(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 676, in _compile    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 500, in transform
    tracer.run()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2149, in run
    super().run()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 810, in run
    and self.step()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2268, in RETURN_VALUE
    self.output.compile_subgraph(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 971, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1168, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1241, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1222, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\__init__.py", line 1729, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 1330, in compile_fx
    return aot_autograd(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\backends\common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 443, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\_aot_autograd\jit_compile_runtime_wrappers.py", line 119, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 1257, in fw_compiler_base
    return inner_compile(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\repro\after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 438, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 714, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\graph.py", line 1307, in compile_to_fn    return self.compile_to_module().call
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\graph.py", line 1250, in compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\graph.py", line 1208, in codegen
    self.scheduler.codegen()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\scheduler.py", line 2339, in codegen
    self.get_backend(device).codegen_nodes(node.get_nodes())  # type: ignore[possibly-undefined]
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 3623, in codegen_nodes
    kernel_group.finalize_kernel(cpp_kernel_proxy, nodes)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 3661, in finalize_kernel
    new_kernel.codegen_loops(code, ws)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 3458, in codegen_loops
    self.codegen_loops_impl(self.loop_nest, code, worksharing)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 1832, in codegen_loops_impl
    gen_loops(loop_nest.root)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 1804, in gen_loops
    gen_loop(loop, in_reduction)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 1817, in gen_loop
    loop_lines = loop.lines()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 3922, in lines
    elif not self.reduction_var_map and codecache.is_gcc():
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codecache.py", line 1001, in is_gcc
    return bool(re.search(r"(gcc|g\+\+)", cpp_compiler()))
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codecache.py", line 944, in cpp_compiler
    return cpp_compiler_search(search)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codecache.py", line 971, in cpp_compiler_search
    raise exc.InvalidCxxCompiler()
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
InvalidCxxCompiler: No working C++ compiler found in torch._inductor.config.cpp.cxx: (None, 'g++')

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

ERROR:app:Exception on /tts [POST]
Traceback (most recent call last):
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\openSource_workspace\chatTTS-ui\app.py", line 118, in tts
    wavs = chat.infer([t for t in text.split("\n") if t.strip()], use_decoder=True,params_infer_code={'spk_emb': rand_spk} ,params_refine_text= {'prompt': prompt})
  File "E:\openSource_workspace\chatTTS-ui\ChatTTS\core.py", line 154, in infer
    text_tokens = refine_text(self.pretrain_models, text, **params_refine_text)['ids']
  File "E:\openSource_workspace\chatTTS-ui\ChatTTS\infer\api.py", line 114, in refine_text
    result = models['gpt'].generate(
  File "E:\openSource_workspace\chatTTS-ui\ChatTTS\model\gpt.py", line 203, in generate
    outputs = self.gpt.forward(**model_input, output_attentions=return_attn)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\transformers\models\llama\modeling_llama.py", line 940, in forward
    causal_mask = self._update_causal_mask(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 676, in _compile    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 500, in transform
    tracer.run()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2149, in run
    super().run()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 810, in run
    and self.step()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2268, in RETURN_VALUE
    self.output.compile_subgraph(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 971, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1168, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1241, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1222, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\__init__.py", line 1729, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 1330, in compile_fx
    return aot_autograd(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\backends\common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 443, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_functorch\_aot_autograd\jit_compile_runtime_wrappers.py", line 119, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 1257, in fw_compiler_base
    return inner_compile(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\repro\after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\liujianglong\anaconda3\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 438, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 714, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\graph.py", line 1307, in compile_to_fn    return self.compile_to_module().call
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\graph.py", line 1250, in compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\graph.py", line 1208, in codegen
    self.scheduler.codegen()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\scheduler.py", line 2339, in codegen
    self.get_backend(device).codegen_nodes(node.get_nodes())  # type: ignore[possibly-undefined]
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 3623, in codegen_nodes
    kernel_group.finalize_kernel(cpp_kernel_proxy, nodes)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 3661, in finalize_kernel
    new_kernel.codegen_loops(code, ws)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 3458, in codegen_loops
    self.codegen_loops_impl(self.loop_nest, code, worksharing)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 1832, in codegen_loops_impl
    gen_loops(loop_nest.root)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 1804, in gen_loops
    gen_loop(loop, in_reduction)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 1817, in gen_loop
    loop_lines = loop.lines()
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codegen\cpp.py", line 3922, in lines
    elif not self.reduction_var_map and codecache.is_gcc():
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codecache.py", line 1001, in is_gcc
    return bool(re.search(r"(gcc|g\+\+)", cpp_compiler()))
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codecache.py", line 944, in cpp_compiler
    return cpp_compiler_search(search)
  File "E:\openSource_workspace\chatTTS-ui\venv\lib\site-packages\torch\_inductor\codecache.py", line 971, in cpp_compiler_search
    raise exc.InvalidCxxCompiler()
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
InvalidCxxCompiler: No working C++ compiler found in torch._inductor.config.cpp.cxx: (None, 'g++')

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by jianchang512** [comment]
打开 app.py,找到 import torch 这行
在下一行粘贴

```
import torch._dynamo
torch._dynamo.config.suppress_errors = True
```
