### ISSUE TITLE
speaker目录下的pt文件为何用不了？

### ISSUE THREAD

**Issue by v-yunbin** [jianchang512/ChatTTS-ui#188]

**Comment by jianchang512** [comment]
![image](https://github.com/user-attachments/assets/de1f7094-aced-4b5c-bb6e-704dd347e021)

**Comment by v-yunbin** [comment]
我用的老版本，我没有用新版本，

**Comment by jianchang512** [comment]
什么叫用不了？不显示？无法选择？使用报错？
报错信息呢

**Comment by v-yunbin** [comment]
从modelscope下载的pt可以用，直接使用speaker目录下的speaker/11.pt，报下面的错：
```
Traceback (most recent call last):
  File "infer_define.py", line 27, in <module>
    wavs = chat.infer(texts,  params_infer_code=params_infer_code, use_decoder=True)
  File "/data/disk1/ybZhang/ChatTTS/ChatTTS/core.py", line 140, in infer
    result = infer_code(self.pretrain_models, text, **params_infer_code, return_hidden=use_decoder)
  File "/data/disk1/ybZhang/ChatTTS/ChatTTS/infer/api.py", line 44, in infer_code
    print(spk_emb.to(device).to(emb.dtype)[None].shape)
AttributeError: 'str' object has no attribute 'to'
```

**Comment by jianchang512** [comment]
拉取了新代码是吧

删掉已有的，重新去下载中
