### ISSUE TITLE
源码安装，执行python3 app.py启动报错

### ISSUE THREAD

**Issue by fuyuhnag168** [jianchang512/ChatTTS-ui#193]
Starting...
no GPU found, use CPU instead
Traceback (most recent call last):
  File "/data/chat-tts-ui/app.py", line 69, in <module>
    chat.load(source="custom",custom_path=CHATTTS_DIR, device=None if device=='default' else device,compile=True if os.getenv('compile','true').lower()!='false' else False)
  File "/data/chat-tts-ui/ChatTTS/core.py", line 126, in load
    return self._load(
  File "/data/chat-tts-ui/ChatTTS/core.py", line 244, in _load
    torch.load(vocos_ckpt_path, weights_only=True, mmap=True)
  File "/usr/local/python3/lib/python3.9/site-packages/torch/serialization.py", line 1032, in load
    raise RuntimeError("mmap can only be used with files saved with "
RuntimeError: mmap can only be used with files saved with `torch.save(/data/chat-tts-ui/models/pzc163/chatTTS/asset/Vocos.pt, _use_new_zipfile_serialization=True), please torch.save your checkpoint with this option in order to use mmap.

**Comment by jianchang512** [comment]
不要使用已有的音色pt，填写音色值，然后重试
