### ISSUE TITLE
运行的时候出错了

### ISSUE THREAD

**Issue by Markreisen** [jianchang512/ChatTTS-ui#199]
发生错误: INTERNAL SERVER ERROR

**Comment by Markreisen** [comment]
Traceback (most recent call last):
  File "flask\app.py", line 1473, in wsgi_app
  File "flask\app.py", line 882, in full_dispatch_request
  File "flask\app.py", line 880, in full_dispatch_request
  File "flask\app.py", line 865, in dispatch_request
  File "app.py", line 245, in tts
  File "ChatTTS\core.py", line 206, in infer
  File "ChatTTS\core.py", line 365, in _infer
  File "ChatTTS\core.py", line 487, in _infer_code
  File "ChatTTS\core.py", line 447, in _apply_spk_emb
AttributeError: 'str' object has no attribute 'to'
ERROR:app:Exception on /tts [POST]
Traceback (most recent call last):
  File "flask\app.py", line 1473, in wsgi_app
  File "flask\app.py", line 882, in full_dispatch_request
  File "flask\app.py", line 880, in full_dispatch_request
  File "flask\app.py", line 865, in dispatch_request
  File "app.py", line 245, in tts
  File "ChatTTS\core.py", line 206, in infer
  File "ChatTTS\core.py", line 365, in _infer
  File "ChatTTS\core.py", line 487, in _infer_code
  File "ChatTTS\core.py", line 447, in _apply_spk_emb
AttributeError: 'str' object has no attribute 'to'
