### ISSUE TITLE
mac启动python3 app.py 提示模块不存在 明明已经有这个模块了

### ISSUE THREAD

**Issue by cztnozuonodie** [jianchang512/ChatTTS-ui#20]
Traceback (most recent call last):
  File "/opt/chattts/app.py", line 3, in <module>
    import ChatTTS
  File "/opt/chattts/ChatTTS/__init__.py", line 1, in <module>
    from .core import Chat
  File "/opt/chattts/ChatTTS/core.py", line 9, in <module>
    from .model.gpt import GPT_warpper
  File "/opt/chattts/ChatTTS/model/gpt.py", line 7, in <module>
    from transformers.cache_utils import Cache
ModuleNotFoundError: No module named 'transformers'

**Comment by jianchang512** [comment]
你可能搞错了虚拟环境。重新安装一遍。
