### ISSUE TITLE
cover-pt.exe 无法运行

### ISSUE THREAD

**Issue by 1ess** [jianchang512/ChatTTS-ui#209]
![61a8625b5f93a8239055704475f9564](https://github.com/user-attachments/assets/7469c5f2-1604-4ff7-bc12-0fffc83423c4)

**Comment by jianchang512** [comment]
不要使用这个转换了，重新填写音色值生成pt吧

**Comment by 1ess** [comment]
填写音色值生成pt，电流声非常重，基本是不可使用的程度了

**Comment by jianchang512** [comment]
更换多个音色值试试
我测试并无问题

**Comment by jianchang512** [comment]
重新下载这个 https://github.com/jianchang512/ChatTTS-ui/releases/download/v0.99/cover-pt.zip

**Comment by 1ess** [comment]
存在其他错误
![图片](https://github.com/user-attachments/assets/1cf62026-e0ae-4d8d-867b-f96ffea8ad84)

**Comment by jianchang512** [comment]
下载 0.99完整包，然后把 cover-pt.exe 放在app.exe 同目录下

**Comment by Todysheep** [comment]
同样的问题，在1.0、1.01升级补丁包中均无法运行
```
Starting...
2024-08-09 10:54:48,547 - modelscope - INFO - PyTorch version 2.1.2+cu118 Found.
2024-08-09 10:54:48,547 - modelscope - INFO - Loading ast index from C:\Users\Administrator\.cache\modelscope\ast_indexer
2024-08-09 10:54:48,548 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 d41d8cd98f00b204e9800998ecf8427e and a total number of 0 components indexed
{'sha256_asset_Decoder_pt': '9964e36e840f0e3a748c5f716fe6de6490d2135a5f5155f4a642d51860e2ec38', 'sha256_asset_DVAE_full_pt': '553eb75763511e23f3e5f86303e2163c5ca775489d637fb635d979c8ae58bbe5', 'sha256_asset_GPT_pt': 'd7d4ee6461ea097a2be23eb40d73fb94ad3b3d39cb64fbb50cb3357fd466cadb', 'sha256_asset_spk_stat_pt': '3228d8a4cbbf349d107a1b76d2f47820865bd3c9928c4bdfe1cefd5c7071105f', 'sha256_asset_tokenizer_pt': 'e911ae7c6a7c27953433f35c44227a67838fe229a1f428503bdb6cd3d1bcc69c', 'sha256_asset_Vocos_pt': '09a670eda1c08b740013679c7a90ebb7f1a97646ea7673069a6838e6b51d6c58'}
check models in custom path C:/Users/Administrator/Desktop/TextGenerate/ChatTTS/models/pzc163/chatTTS failed.
开始转换 seed_11_restored_emb.pt
Traceback (most recent call last):
  File "cover-pt.py", line 86, in <module>
AttributeError: 'Chat' object has no attribute '_encode_spk_emb'
[15532] Failed to execute script 'cover-pt' due to unhandled exception!
```

**Comment by jianchang512** [comment]
https://github.com/jianchang512/ChatTTS-ui/issues/215

重新下载 cover-pt.exe  https://github.com/jianchang512/ChatTTS-ui/releases/download/v1.0/cover-pt.zip

**Comment by Todysheep** [comment]
问题未解决，版本1.0(下载渠道123网盘，[cover-pt下载渠道](https://github.com/jianchang512/ChatTTS-ui/releases/download/v1.0/cover-pt.zip))：
```
C:\Users\Administrator\Desktop\TextGenerate\ChatTTS> ./cover-pt.exe
Starting...
2024-08-09 17:05:56,217 - modelscope - INFO - PyTorch version 2.1.2+cu118 Found.
2024-08-09 17:05:56,218 - modelscope - INFO - Loading ast index from C:\Users\Administrator\.cache\modelscope\ast_indexer
2024-08-09 17:05:56,218 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 d41d8cd98f00b204e9800998ecf8427e and a total number of 0 components indexed
{'sha256_asset_Decoder_pt': '9964e36e840f0e3a748c5f716fe6de6490d2135a5f5155f4a642d51860e2ec38', 'sha256_asset_DVAE_full_pt': '553eb75763511e23f3e5f86303e2163c5ca775489d637fb635d979c8ae58bbe5', 'sha256_asset_GPT_pt': 'd7d4ee6461ea097a2be23eb40d73fb94ad3b3d39cb64fbb50cb3357fd466cadb', 'sha256_asset_spk_stat_pt': '3228d8a4cbbf349d107a1b76d2f47820865bd3c9928c4bdfe1cefd5c7071105f', 'sha256_asset_tokenizer_pt': 'e911ae7c6a7c27953433f35c44227a67838fe229a1f428503bdb6cd3d1bcc69c', 'sha256_asset_Vocos_pt': '09a670eda1c08b740013679c7a90ebb7f1a97646ea7673069a6838e6b51d6c58'}
check models in custom path C:/Users/Administrator/Desktop/TextGenerate/ChatTTS/models/pzc163/chatTTS failed.
开始转换 seed_11_restored_emb.pt
Traceback (most recent call last):
  File "cover-pt.py", line 86, in <module>
AttributeError: 'Chat' object has no attribute '_encode_spk_emb'
[20236] Failed to execute script 'cover-pt' due to unhandled exception!
```
数据结构如下：
```
asset
| 若干模型
speaker
| seed_742_restored_emb.pt
| seed_11_restored_emb.pt
| ...
app.exe
cover-pt.exe
```

**Comment by jianchang512** [comment]
重新 下载  https://github.com/jianchang512/ChatTTS-ui/releases/download/v1.0/cover-pt.zip

**Comment by jianchang512** [comment]
https://github.com/jianchang512/ChatTTS-ui/releases/download/v1.0/cover-pt0.1.zip

**Comment by rob188** [comment]
> https://github.com/jianchang512/ChatTTS-ui/releases/download/v1.0/cover-pt0.1.zip

(venv) D:\chattts\chatTTS-ui>cover-pt.exe
Error loading Python DLL 'D:\chattts\chatTTS-ui\_internal\python310.dll'.
LoadLibrary: ?????????

**Comment by rob188** [comment]
> https://github.com/jianchang512/ChatTTS-ui/releases/download/v1.0/cover-pt0.1.zip
有cover-pt.py 新版本的源码吗

**Comment by jianchang512** [comment]
exe只能用在预打包版本里，源码重新拉取
