### ISSUE TITLE
请问大佬这是什么问题呀？

### ISSUE THREAD

**Issue by rock-vs-xi** [jianchang512/ChatTTS-ui#210]
[2024-08-06 17:06:32,676] ERROR in app: Exception on /tts [POST]
Traceback (most recent call last):
  File "D:\chattts\ChatTTS-ui-main\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\chattts\ChatTTS-ui-main\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\chattts\ChatTTS-ui-main\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\chattts\ChatTTS-ui-main\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\chattts\ChatTTS-ui-main\app.py", line 223, in tts
    rand_spk = chat.sample_random_speaker()
  File "D:\chattts\ChatTTS-ui-main\ChatTTS\core.py", line 161, in sample_random_speaker
    return self.tokenizer._encode_spk_emb(self._sample_random_speaker())
AttributeError: 'Chat' object has no attribute 'tokenizer'
ERROR:app:Exception on /tts [POST]
Traceback (most recent call last):
  File "D:\chattts\ChatTTS-ui-main\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\chattts\ChatTTS-ui-main\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\chattts\ChatTTS-ui-main\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\chattts\ChatTTS-ui-main\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\chattts\ChatTTS-ui-main\app.py", line 223, in tts
    rand_spk = chat.sample_random_speaker()
  File "D:\chattts\ChatTTS-ui-main\ChatTTS\core.py", line 161, in sample_random_speaker
    return self.tokenizer._encode_spk_emb(self._sample_random_speaker())
AttributeError: 'Chat' object has no attribute 'tokenizer'

**Comment by kidcrazequ** [comment]
更新到0.99版后会有这个问题，等作者更新吧

**Comment by rock-vs-xi** [comment]
> 更新到0.99版本后会有这个问题，等作者更新吧

好的 谢谢回复

**Comment by jianchang512** [comment]
下载完整包覆盖

**Comment by jianchang512** [comment]
如果是源码部署，也需要下载更新包，然后将里面的models文件夹覆盖目录下的同名models

**Comment by rock-vs-xi** [comment]
> models 文件夹也更新了吗
> 
> 下载更新包，将里面的models文件夹覆盖，需要更新模型

好的
