### ISSUE TITLE
macos intel 发生错误: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by p-eve** [jianchang512/ChatTTS-ui#226]
[2024-08-13 22:12:57,923] ERROR in app: Exception on /tts [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/chattts-ui/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/chattts-ui/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/chattts-ui/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/chattts-ui/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vincent/Documents/code/AI/ChatTTS-ui/app.py", line 264, in tts
    wavs = chat.infer(
           ^^^^^^^^^^^
  File "/Users/vincent/Documents/code/AI/ChatTTS-ui/ChatTTS/core.py", line 233, in infer
    return next(res_gen)
           ^^^^^^^^^^^^^
  File "/Users/vincent/Documents/code/AI/ChatTTS-ui/ChatTTS/core.py", line 354, in _infer
    assert self.has_loaded(use_decoder=use_decoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by p-eve** [comment]
更新 asset 里面的所有文件后可以了

**Comment by coderyqy** [comment]
可以参考一下我的解决方案：
我是直接下载win整合包，并且把all-models也下载下来，解压win整合包后，不要点击app.exe运行，先把all-models中的asset文件夹复制到win整合包，再点击点击app.exe运行。因为我尝试过直接运行app.exe生成的asset文件，好像有问题。
