### ISSUE TITLE
OSError: [Errno 28] inotify watch limit reached

### ISSUE THREAD

**Issue by chuan-mt** [jianchang512/ChatTTS-ui#231]
Traceback (most recent call last):
  File "/opt/conda/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/streamlit/web/cli.py", line 234, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/opt/conda/lib/python3.10/site-packages/streamlit/web/cli.py", line 270, in _main_run
    bootstrap.run(file, is_hello, args, flag_options)
  File "/opt/conda/lib/python3.10/site-packages/streamlit/web/bootstrap.py", line 382, in run
    _install_pages_watcher(main_script_path)
  File "/opt/conda/lib/python3.10/site-packages/streamlit/web/bootstrap.py", line 358, in _install_pages_watcher
    watch_dir(
  File "/opt/conda/lib/python3.10/site-packages/streamlit/watcher/path_watcher.py", line 151, in watch_dir
    return _watch_path(
  File "/opt/conda/lib/python3.10/site-packages/streamlit/watcher/path_watcher.py", line 126, in _watch_path
    watcher_class(
  File "/opt/conda/lib/python3.10/site-packages/streamlit/watcher/event_based_path_watcher.py", line 95, in __init__
    path_watcher.watch_path(
  File "/opt/conda/lib/python3.10/site-packages/streamlit/watcher/event_based_path_watcher.py", line 173, in watch_path
    folder_handler.watch = self._observer.schedule(
  File "/opt/conda/lib/python3.10/site-packages/watchdog/observers/api.py", line 323, in schedule
    emitter.start()
  File "/opt/conda/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 92, in start
    self.on_thread_start()
  File "/opt/conda/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 125, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive, event_mask)
  File "/opt/conda/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
    self._inotify = Inotify(path, recursive, event_mask)
  File "/opt/conda/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 174, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/opt/conda/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 380, in _add_dir_watch
    self._add_watch(path, mask)
  File "/opt/conda/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 401, in _add_watch
    Inotify._raise_error()
  File "/opt/conda/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 413, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached

**Comment by jianchang512** [comment]
Text too long and out of memory?
