### ISSUE TITLE
Linux 22.04，pytorch 2.2.2，cuda 12.1，报错：RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_bmm)

### ISSUE THREAD

**Issue by vxzhong** [jianchang512/ChatTTS-ui#234]
源码安装，跑在cuda上，请求tts接口，如下报错，请教是什么原因：

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/miniconda3/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/miniconda3/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/miniconda3/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/autodl-tmp/ChatTTS-ui/app.py", line 264, in tts
    wavs = chat.infer(
  File "/root/autodl-tmp/ChatTTS-ui/ChatTTS/core.py", line 233, in infer
    return next(res_gen)
  File "/root/autodl-tmp/ChatTTS-ui/ChatTTS/core.py", line 386, in _infer
    for result in self._infer_code(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/autodl-tmp/ChatTTS-ui/ChatTTS/model/gpt.py", line 458, in generate
    outputs: BaseModelOutputWithPast = self.gpt(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 977, in forward
    position_embeddings = self.rotary_emb(hidden_states, position_ids)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 209, in forward
    freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_bmm)
ERROR:app:Exception on /tts [POST]

**Comment by jianchang512** [comment]
打开 .env 将 device 设为 cpu 试试
