### ISSUE TITLE
各位老大，我用mac教程下载到最后打开app说没有module named ’pandas'

### ISSUE THREAD

**Issue by jingjing825** [jianchang512/ChatTTS-ui#247]
(venv) (base) bobo@joushoushous-MacBook-Pro chattts % python3 app.py
Starting...
Traceback (most recent call last):
  File "/Users/bobo/data/chattts/app.py", line 37, in <module>
    from uilib import utils,VERSION
  File "/Users/bobo/data/chattts/uilib/utils.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

这个怎么打开啊求求了各位大佬

**Comment by jingjing825** [comment]
pip3 install pandas

暂时运行起来了
