### ISSUE TITLE
项目启动报错 Macos

### ISSUE THREAD

**Issue by fanheshe** [jianchang512/ChatTTS-ui#40]
eeejdeMac-mini:chattts eeejeeej$ python3 app.py
Traceback (most recent call last):
  File "/Users/eeejeeej/Documents/Github/chattts/app.py", line 3, in <module>
    import ChatTTS
  File "/Users/eeejeeej/Documents/Github/chattts/ChatTTS/__init__.py", line 1, in <module>
    from .core import Chat
  File "/Users/eeejeeej/Documents/Github/chattts/ChatTTS/core.py", line 7, in <module>
    from vocos import Vocos
ModuleNotFoundError: No module named 'vocos'

**Comment by jianchang512** [comment]
pip install -r requirements.txt

**Comment by fanheshe** [comment]
重新安装后报错：
(venv) eeejdeMac-mini:chatTTS-ui eeejeeej$ python3 app.py
Traceback (most recent call last):
  File "/Users/eeejeeej/Documents/Github/chatTTS-ui/app.py", line 42, in <module>
    from waitress import serve
ModuleNotFoundError: No module named 'waitress'

**Comment by fanheshe** [comment]
重新安装后解决了，感谢
