### ISSUE TITLE
macos报错:ModuleNotFoundError: No module named 'torch._dynamo'

### ISSUE THREAD

**Issue by dingdaoyi** [jianchang512/ChatTTS-ui#64]
我按照mac的命令运行下去, 报这个错
Traceback (most recent call last):
  File "/Users/dingyunwei/workspace/tools/chattts/chatTTS-ui/app.py", line 6, in <module>
    import torch._dynamo
ModuleNotFoundError: No module named 'torch._dynamo'

**Comment by jianchang512** [comment]
pip3 install torch torchaudio 

这个执行了吗
如果执行了，将 app.py中 
```
import torch._dynamo
torch._dynamo.config.suppress_errors = True
torch._dynamo.config.cache_size_limit = 64
torch._dynamo.config.suppress_errors = True
```

这几行代码删掉

**Comment by dingdaoyi** [comment]
出现这个问题了, 跟他运行同样命令报错
https://github.com/jianchang512/ChatTTS-ui/issues/60#issue-2330098399
-> % pip3 install soundfile                
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: soundfile in ./venv/lib/python3.10/site-packages (0.12.1)
Requirement already satisfied: cffi>=1.0 in ./venv/lib/python3.10/site-packages (from soundfile) (1.16.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.10/site-packages (from cffi>=1.0->soundfile) (2.22)
(venv) 
**@** [17:42:12] [~/workspace/tools/chattts/chatTTS-ui] [main *]
-> % python3 app.py        
Traceback (most recent call last):
  File "/Users/**/workspace/tools/chattts/chatTTS-ui/app.py", line 36, in <module>
    import soundfile as sf
ModuleNotFoundError: No module named 'soundfile'
(venv)

**Comment by jianchang512** [comment]
是部署没有执行  pip install -r requirements.txt 命令

**Comment by jianchang512** [comment]
先执行 brew install libsndfile

再执行 pip install soundfile

**Comment by dingdaoyi** [comment]
这个问题我看了下, 是python3.10 以上版本会报错, 换成3.10 好了
