### ISSUE TITLE
windows11运行报错

### ISSUE THREAD

**Issue by guozhenchang** [jianchang512/ChatTTS-ui#79]
2024-06-04 16:33:51,375 - modelscope - INFO - Loading done! Current index file version is 1.14.0, with md5 1de6771b92411d1485eda0c258b9dc21 and a total number of 976 components indexed
INFO:ChatTTS.core:Load from local: D:/chattts/chatTTS-ui/models/pzc163/chatTTS
Traceback (most recent call last):
  File "D:\chattts\chatTTS-ui\app.py", line 38, in <module>
    chat.load_models(source="local",local_path=CHATTTS_DIR, compile=True if os.getenv('compile','true').lower()!='false' else False)
  File "D:\chattts\chatTTS-ui\ChatTTS\core.py", line 62, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()}, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chattts\chatTTS-ui\venv\Lib\site-packages\omegaconf\omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\chattts\\chatTTS-ui\\models\\pzc163\\chatTTS\\config\\path.yaml'

**Comment by jianchang512** [comment]
#80

**Comment by guozhenchang** [comment]
模型不完整，下载 https://www.modelscope.cn/models/pzc163/chatTTS 放到models解决了
