### ISSUE TITLE
使用conda创建虚拟py环境运行报错

### ISSUE THREAD

**Issue by chenisvert** [jianchang512/ChatTTS-ui#83]
ERROR:app:Exception on /tts [POST]
Traceback (most recent call last):
  File "/home/chen/anaconda3/envs/chat/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chen/anaconda3/envs/chat/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chen/anaconda3/envs/chat/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chen/anaconda3/envs/chat/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/data/chatTTS-ui/app.py", line 156, in tts
    wavs = chat.infer(new_text, use_decoder=True, skip_refine_text=True if int(skip_refine)==1 else False,params_infer_code={
NameError: name 'chat' is not defined

请问这个如何解决呢

**Comment by chenisvert** [comment]
创建的环境名称叫chat,版本是py 3.10

**Comment by jianchang512** [comment]
执行的什么命令
哪步操作报错

重新git pull

看下仓库源码部署说明

**Comment by fsjoy52** [comment]
我用conda部署好了，但是生成时无法调用显卡参与运算，全是CPU在跑

**Comment by jianchang512** [comment]
显存低于4G只使用CPU

**Comment by chenisvert** [comment]
> 执行的什么命令 哪步操作报错
> 
> 重新git pull
> 
> 看下仓库源码部署说明

我执行了 python webui.py 之后webui可以跑起来，但是生成音频报错

**Comment by fsjoy52** [comment]
> 显存低于4G只使用CPU

按照你新改的pip install torch==2.2.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu118，CUDA加速已经跑起来了，感谢

**Comment by monkdharma** [comment]
我也遇到了一样的错误，有解决方法了吗？
```
ERROR:app:Exception on /tts [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/workspace/app.py", line 160, in tts
    wavs = chat.infer(new_text, use_decoder=True, skip_refine_text=True if int(skip_refine)==1 else False,params_infer_code={
NameError: name 'chat' is not defined
```
