### ISSUE TITLE
mac python3.10 报错 lamaModel.forward() got an unexpected keyword argument 'cache_position'

### ISSUE THREAD

**Issue by cy486** [jianchang512/ChatTTS-ui#84]
TypeError: LlamaModel.forward() got an unexpected keyword argument 'cache_position'

**Comment by cy486** [comment]
解决了 缺少transformers 环境
https://github.com/huggingface/transformers/blob/main/README_zh-hans.md
执行 conda install conda-forge::transformers 成了

**Comment by Ansen88** [comment]
我也出现了这个问题，按照上面的方式安装后出现了新的问题：
Traceback (most recent call last):
  File "/home/anlj/work/src/ChatTTS-ui-main/app.py", line 14, in <module>
    import ChatTTS
  File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/__init__.py", line 1, in <module>
    from .core import Chat
  File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/core.py", line 8, in <module>
    from vocos import Vocos
  File "/home/anlj/.local/lib/python3.11/site-packages/vocos/__init__.py", line 1, in <module>
    from vocos.pretrained import Vocos
  File "/home/anlj/.local/lib/python3.11/site-packages/vocos/pretrained.py", line 7, in <module>
    from huggingface_hub import hf_hub_download
ImportError: cannot import name 'hf_hub_download' from 'huggingface_hub' (/home/anlj/.local/lib/python3.11/site-packages/huggingface_hub/__init__.py)

**Comment by wisyemily** [comment]
> 我也出现了这个问题，按照上面的方式安装后出现了新的问题（我的系统是 linux）： Traceback (most recent call last): File "/home/anlj/work/src/ChatTTS-ui-main/app.py", line 14, in import ChatTTS File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/**init**.py", line 1, in from .core import Chat File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/core.py", line 8, in from vocos import Vocos File "/home/anlj/.local/lib/python3.11/site-packages/vocos/**init**.py", line 1, in from vocos.pretrained import Vocos File "/home/anlj/.local/lib/python3.11/site-packages/vocos/pretrained.py", line 7, in from huggingface_hub import hf_hub_download ImportError: cannot import name 'hf_hub_download' from 'huggingface_hub' (/home/anlj/.local/lib/python3.11/site-packages/huggingface_hub/**init**.py)

这个问题怎么解决？我前几天能正常运行，今天一直报这个错，重新安装了环境依然报这个错误。

**Comment by jianchang512** [comment]
`pip3 install --upgrade huggingface_hub`

**Comment by coderyqy** [comment]
可以参考一下我的解决方案：
我是直接下载win整合包，并且把all-models也下载下来，解压win整合包后，不要点击app.exe运行，先把all-models中的asset文件夹复制到win整合包，再点击点击app.exe运行。因为我尝试过直接运行app.exe生成的asset文件，好像有问题。
