### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by TheSundowners** [jianchang512/ChatTTS-ui#9]
Traceback (most recent call last):
  File "D:\chattts\chatTTS-ui\app.py", line 10, in <module>
    import soundfile as sf
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\soundfile.py", line 17, in <module>
    from _soundfile import ffi as _ffi
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\_soundfile.py", line 2, in <module>
    import _cffi_backend
ModuleNotFoundError: No module named '_cffi_backend'

**Comment by jianchang512** [comment]
源码部署？

试试执行   `pip uninstall cffi` 
再执行 `pip install -U cffi`

**Comment by TheSundowners** [comment]
好了，感谢。
