### ISSUE TITLE
部署成功后，在点击合成时提示“发生错误: INTERNAL SERVER ERROR”

### ISSUE THREAD

**Issue by Ansen88** [jianchang512/ChatTTS-ui#94]
错误信息：
voice=2000,custom_voice=2000
固定音色 seed=2000
result=['大家好'],len=1
  0%|                                                                                       | 0/384 [00:00<?, ?it/s]
[2024-06-05 14:37:48,355] ERROR in app: Exception on /tts [POST]
Traceback (most recent call last):
  File "/home/anlj/.conda/envs/ChatTTS/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/.conda/envs/ChatTTS/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/.conda/envs/ChatTTS/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/.conda/envs/ChatTTS/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/work/src/ChatTTS-ui-main/app.py", line 156, in tts
    wavs = chat.infer(new_text, use_decoder=True, skip_refine_text=True if int(skip_refine)==1 else False,params_infer_code={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/core.py", line 158, in infer
    text_tokens = refine_text(self.pretrain_models, text, **params_refine_text)['ids']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/infer/api.py", line 114, in refine_text
    result = models['gpt'].generate(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/model/gpt.py", line 203, in generate
    outputs = self.gpt.forward(**model_input, output_attentions=return_attn)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LlamaModel.forward() got an unexpected keyword argument 'cache_position'
ERROR:app:Exception on /tts [POST]
Traceback (most recent call last):
  File "/home/anlj/.conda/envs/ChatTTS/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/.conda/envs/ChatTTS/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/.conda/envs/ChatTTS/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/.conda/envs/ChatTTS/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/work/src/ChatTTS-ui-main/app.py", line 156, in tts
    wavs = chat.infer(new_text, use_decoder=True, skip_refine_text=True if int(skip_refine)==1 else False,params_infer_code={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/core.py", line 158, in infer
    text_tokens = refine_text(self.pretrain_models, text, **params_refine_text)['ids']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/infer/api.py", line 114, in refine_text
    result = models['gpt'].generate(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anlj/work/src/ChatTTS-ui-main/ChatTTS/model/gpt.py", line 203, in generate
    outputs = self.gpt.forward(**model_input, output_attentions=return_attn)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LlamaModel.forward() got an unexpected keyword argument 'cache_position'

**Comment by jianchang512** [comment]
#cache_position
